### ISSUE TITLE
HELP - sync with sonarr yaml and plex, fails with a language different from en

### ISSUE THREAD

**Issue by Derekcde** [TitleCardMaker/TitleCardMaker#399]
### Installation

Docker - master tag

### Describe your Problem

Good morning,

I have a question, I have titlecardmaker in a docker with tautulli, I followed the tutorial to update the episode posters once the episode has been viewed.
It works except for a few series which have different names in English (sonarr's default language) and in French (the plex configuration language).
Example: the Netflix series "Class Act" in French it is called "Tapie" when I watch an episode tautulli launches the creation of the text file, then the file is read and deleted but the poster of the episode does not change , it remains in "blur" mode.

I tried adding the "name" parameter to match the name that should get like this:
```
   Class Act (2023): {template: global_template, name: Tapie (2023), media_directory: '/config/cards/Class
       Act (2023) {imdb-tt27921612}'}
```

But no change, even if I no longer have any warnings in the log.
I have the impression that it worked before the last update but I'm not sure.

How can I make this work with series that have a different name between sonnar(en) and plex(fr)?

Thank you in advance for your answer

### Preference File

```yaml
options:
  source: /config/source/
  series: /config/yaml/sync_sonarr_seriestv.yml
  card_type: standard
  episode_data_source: sonarr
  image_source_priority: plex, tmdb
  filename_format: "{full_name} - S{season:02}E{episode:02} - {title}"
  validate_fonts: true
  season_folder_format: "Season {season:02}"
  sync_specials: true
  language_codes: 
  - fr
plex:
  url: http://
  verify_ssl: false
  token: 
  watched_style: unique
  unwatched_style: blur
  integrate_with_pmm_overlays: true
  sync:
  - card_directory: /config/cards
  - file: /config/yaml/sync_plex_seriestv.yml
    add_template: global_template
    libraries:
    - Séries TV
tautulli:
  url: http://
  verify_ssl: false
  api_key: 
  update_script: /tautulli/update_card.sh
  username: "ClD"
  agent_name: Update TitleCardMaker
  script_timeout: 120 
sonarr:
  url: http://
  verify_ssl: false
  api_key: 
  sync:
  - card_directory: /config/cards/
    downloaded_only: true
    mode: match
  - file: /config/yaml/sync_sonarr_seriestv.yml
    add_template: global_template
tmdb:
  api_key: 
  retry_count: 3
  logo_language_priority: fr
```

### Series YAML

```yaml
templates:
  global_template:
    watched_style: unique
    unwatched_style: blur
    library: SeriesTV
    path: /config/cards
    episode_data_source: plex
    translation:
      language: fr
      key: preferred_title
libraries:
  SeriesTV:
    path: /config/cards
    library_name: Séries TV
libraries:
   TV series:
     path: /config/cards
     library_name: TV Series
series:
  Class Act (2023): {template: global_template, media_directory: '/config/cards/Class
      Act (2023) {imdb-tt27921612}'}
```

### Debug Log

[DEBUG] [09-22-23 13:07:30.020] Rating key 68012 -> 1 item(s)
[INFO] [09-22-23 13:07:30.020] Reading series YAML file "/config/yaml/sync_sonarr_seriestv.yml"..
[WARNING] [09-22-23 13:07:30.147] Cannot update card for "Tapie (2023)" S01E03 within library "Séries TV" - no matching YAML entry was found
[INFO] [09-22-23 13:07:30.148] Sleeping until 13:11:30 2023-09-22
[DEBUG] [09-22-23 13:11:30.148] Update list does not exist
