### ISSUE TITLE
HELP - How to translate Season and Episode?

### ISSUE THREAD

**Issue by Jorman** [TitleCardMaker/TitleCardMaker#476]
### Installation

Docker - develop tag

### Describe your Problem

Hi, I recently installed TitleCardMaker and I'm trying to set it up, I don't have any special needs, I'm fine with applying the standard card for each episode, however, I'm having a hard time with having the translation of Season and Episode, I can't get them in my language.

Actually I've been having a hard time with the title names as well, but by searching I saw that moving to the dev, it solved the various problems

### Screenshots

![Poirot (1989) - S03E11](https://github.com/user-attachments/assets/06ead5b0-ebf5-4fc9-a701-5d55eb847312)

### Preference File

```yaml
options:
  source: /config/source/
  series: /config/plex-serie-tv.yml
  episode_data_source: plex
  # season_folder_format: "Stagione {season:02}"
  # episode_text_format: "Puntata {episode_number}"
  sync_specials: true
  language_codes:
  - it
  # translation:
  # - language: it

plex:
  url: http://10.0.0.100:32400
  token: token
  watched_style: grayscale
  unwatched_style: unique
  sync:
  - card_directory: /config/cards
  - file: /config/plex-serie-tv.yml
    libraries:
    - Serie TV

# sonarr:
#   url: http://10.0.0.100:8989
#   api_key: api
#   sync:
#   - card_directory: /config/cards
#     downloaded_only: true
#     monitored_only: false
#     plex_libraries:
#       /data/Multimedia/Serie Tv: Serie TV
#   - file: /config/sonarr-serie-tv.yml
#     series_type: standard

tmdb:
  api_key: api
  skip_localized_images: true
  logo_language_priority: it-IT, en
```

### Debug Log

[maker.log](https://github.com/user-attachments/files/16576089/maker.log)

**Comment by CollinHeist** [comment]
@Jorman Hey - so the season and episode text are controlled by two separate settings. The [season titles](https://github.com/CollinHeist/TitleCardMaker/wiki/Series-YAML-Files#season-titles) and [episode text format](https://github.com/CollinHeist/TitleCardMaker/wiki/Episode-Text). Most likely you will want to add the non-English versions of these to a template like so:

```yaml
templates:
  non-english:
    episode_text_format: "Episodio {episode_number}"
    seasons:
      1: My Custom Title 1
      2: My Custom Title 2
      # repeat for as many seasons as you might need
    
series:
  Example Series (2024):
    template: non-english
```

Let me know if that doesn't work for you
